// 사이트 정보
export const SITE_INFO = {
  name: '리브성형외과',
  nameEn: 'LIV Plastic Surgery',
  slogan: 'Slow Aging, Natural Beauty',
  phone: '02-797-2773',
  phoneInternational: '+82-2-797-2773',
  email: 'info@livps.co.kr',
  address: {
    ko: '서울특별시 서초구 나루터로 80 자은빌딩 4층',
    en: '4F, Jaeun Building, 80 Naruteo-ro, Seocho-gu, Seoul, Korea',
  },
  postalCode: '06536',
  coordinates: {
    lat: 37.5155786,
    lng: 127.0184697,
  },
} as const;

// 영업시간
export const BUSINESS_HOURS = {
  weekday: { open: '10:00', close: '19:00' },
  saturday: { open: '10:00', close: '16:00' },
  sunday: null, // 휴무
} as const;

// SNS 링크
export const SOCIAL_LINKS = {
  kakao: 'https://pf.kakao.com/_hgFwn', // 리브성형외과 카카오톡 채널
  instagram: 'https://www.instagram.com/livps_official/',
  naver: 'https://blog.naver.com/liv_clinic',
  youtube: 'https://www.youtube.com/@리브성형외과',
  wechat: 'weixin://dl/chat?livps', // WeChat ID: livps
  line: 'https://line.me/R/ti/p/@livps', // LINE ID: @livps
} as const;

// 인증 정보
export const CERTIFICATIONS = [
  {
    id: 'ulthera',
    name: '울쎄라피 프라임 정품 인증',
    nameEn: 'Ultherapy Prime Certified',
    logo: '/images/certifications/ulthera.png',
    link: 'https://merz.co.kr/',
  },
  {
    id: 'thermage',
    name: '써마지 FLX 파트너',
    nameEn: 'Thermage FLX Partner',
    logo: '/images/certifications/thermage.png',
    link: 'https://www.thermage.co.kr/',
  },
] as const;

// 4대 핵심 가치
export const CORE_VALUES = [
  {
    id: 'natural',
    title: 'Natural Beauty',
    titleKo: '자연스러운 아름다움',
    description: '과하지 않은, 본연의 아름다움을 추구합니다',
    image: '/images/values/natural-beauty.png',
  },
  {
    id: 'expertise',
    title: 'Clinical Expertise',
    titleKo: '전문적 기술',
    description: '풍부한 경험과 노하우로 최상의 결과를 제공합니다',
    image: '/images/values/clinical-expertise.png',
  },
  {
    id: 'safety',
    title: 'Safety & Ethical Care',
    titleKo: '안전과 윤리',
    description: '정품정량 원칙과 철저한 안전 관리를 준수합니다',
    image: '/images/values/safety-ethics.png',
  },
  {
    id: 'tailored',
    title: 'Tailored Aging',
    titleKo: '맞춤 안티에이징',
    description: '개인별 맞춤 솔루션으로 최적의 결과를 설계합니다',
    image: '/images/values/tailored-aging.png',
  },
] as const;

// 시그니처 프로그램
export const SIGNATURE_PROGRAMS = [
  {
    id: 'lifting',
    title: 'LIFTING',
    subtitle: '울쎄라피 프라임 & 써마지',
    description: '비수술 리프팅의 정점, 프리미엄 장비로 자연스러운 리프팅',
    href: '/signature/lifting',
  },
  {
    id: 'petit',
    title: 'PETIT',
    subtitle: '필러 & 보톡스',
    description: '섬세한 터치로 완성하는 볼륨과 윤곽',
    href: '/signature/petit',
  },
  {
    id: 'care',
    title: 'CARE',
    subtitle: '메디컬 스킨케어',
    description: '피부 본연의 건강함을 되찾는 맞춤 케어',
    href: '/signature/care',
  },
] as const;

// 장비 목록 (회의록 기준 순서)
export const EQUIPMENT_LIST = [
  { id: 'ulthera', name: 'Ultherapy Prime', nameKo: '울쎄라피 프라임' },
  { id: 'thermage', name: 'Thermage FLX', nameKo: '써마지 FLX' },
  { id: 'density', name: 'Density', nameKo: '덴서티' },
  { id: 'shurink', name: 'Shurink', nameKo: '슈링크' },
  { id: 'inmode', name: 'InMode', nameKo: '인모드' },
  { id: 'potenza', name: 'Potenza', nameKo: '포텐자' },
  { id: 'clarity', name: 'Clarity II', nameKo: '클래리티 II' },
  { id: 'lucas', name: 'LUCAS Laser', nameKo: '루카스 레이저' },
  { id: 'co2', name: 'CO2 Laser', nameKo: 'CO2 레이저' },
  { id: 'ulblanc', name: 'Ulblanc', nameKo: '울블랑' },
] as const;

// 시술 정보
export const TREATMENTS = {
  // 리프팅 시술
  lifting: {
    ulthera: {
      id: 'ulthera',
      category: 'lifting',
      name: '울쎄라피 프라임',
      nameEn: 'Ultherapy Prime',
      tagline: 'FDA 승인 초음파 리프팅 – 깊은 층부터 탄탄하게',
      shortDesc: '미국 FDA와 국내 식약처 승인, HIFU 리프팅의 글로벌 스탠다드',
      heroImage: '/images/treatments/ulthera-hero.jpg',
      description: '울쎄라피 프라임은 미국 FDA에서 유일하게 리프팅 효과를 승인받은 HIFU(고강도 집속 초음파) 장비입니다. 피부 깊은 층인 SMAS까지 에너지를 전달하여 콜라겐 재생을 촉진하고, 자연스러운 리프팅 효과를 제공합니다.',
      benefits: [
        { title: 'FDA 유일 승인', desc: '리프팅 효과를 인정받은 유일한 HIFU 장비' },
        { title: 'DeepSEE 기술', desc: '시술 부위를 실시간으로 확인하며 정확한 시술' },
        { title: '자연스러운 결과', desc: '점진적 콜라겐 재생으로 3-6개월에 걸쳐 개선' },
        { title: '다운타임 최소화', desc: '일상생활에 바로 복귀 가능' },
      ],
      process: [
        { step: 1, title: '상담', desc: '피부 상태 분석 및 시술 계획 수립' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 피부 정돈' },
        { step: 3, title: '마취', desc: '편안한 시술을 위한 마취 크림 도포' },
        { step: 4, title: '시술', desc: 'DeepSEE로 확인하며 정밀 시술' },
        { step: 5, title: '마무리', desc: '시술 부위 진정 및 애프터케어 안내' },
      ],
      duration: '60-90분',
      anesthesia: '마취 크림 (30분)',
      recovery: '즉시 일상 복귀 가능',
      results: '3-6개월에 걸쳐 점진적 개선, 1-2년 유지',
      targetAreas: ['이마', '눈가', '볼', '턱선', '목'],
      idealFor: [
        '비수술로 리프팅을 원하는 분',
        '처진 피부, 탄력 저하가 고민인 분',
        '자연스러운 변화를 원하는 분',
        '다운타임 없이 시술받고 싶은 분',
      ],
      cautions: [
        '시술 후 약간의 붓기, 홍조가 있을 수 있음',
        '시술 부위에 따라 일시적 감각 이상 가능',
        '임산부, 수유부는 시술 불가',
        '시술 부위에 금속 임플란트가 있는 경우 상담 필요',
      ],
      faqs: [
        { q: '울쎄라피 프라임 시술은 얼마나 아픈가요?', a: '마취 크림을 바르고 시술하기 때문에 대부분 견딜 만한 수준입니다. 통증에 민감하신 분은 추가적인 통증 조절이 가능합니다.' },
        { q: '효과는 언제부터 나타나나요?', a: '시술 직후에도 약간의 리프팅 효과를 느낄 수 있으며, 콜라겐 재생에 따라 3-6개월에 걸쳐 점진적으로 개선됩니다.' },
        { q: '울쎄라피 프라임과 써마지의 차이는 무엇인가요?', a: '울쎄라피 프라임은 HIFU(초음파), 써마지는 RF(고주파) 에너지를 사용합니다. 울쎄라피 프라임은 깊은 층의 리프팅에, 써마지는 전체적인 탄력 개선에 효과적입니다. 두 시술을 병행하면 시너지 효과를 볼 수 있습니다.' },
      ],
      relatedTreatments: ['thermage', 'shurink', 'thread'],
    },
    thermage: {
      id: 'thermage',
      category: 'lifting',
      name: '써마지 FLX',
      nameEn: 'Thermage FLX',
      tagline: '4세대 프리미엄 고주파 리프팅',
      shortDesc: '전 세계가 인정한 고주파 리프팅의 명품',
      heroImage: '/images/treatments/thermage-hero.jpg',
      description: '써마지 FLX는 최신 4세대 고주파 리프팅 장비로, AccuREP 기술을 통해 피부 상태에 맞는 최적의 에너지를 자동으로 조절합니다. 콜라겐 수축과 재생을 유도하여 전체적인 피부 탄력을 개선합니다.',
      benefits: [
        { title: 'AccuREP 기술', desc: '피부 임피던스를 실시간 측정하여 최적 에너지 전달' },
        { title: '시술 시간 단축', desc: '기존 대비 25% 빠른 시술 시간' },
        { title: '통증 감소', desc: '진동 기술로 시술 중 불편감 최소화' },
        { title: '균일한 효과', desc: '고른 에너지 전달로 균일한 리프팅 효과' },
      ],
      process: [
        { step: 1, title: '상담', desc: '피부 상태 분석 및 시술 계획 수립' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 피부 정돈' },
        { step: 3, title: '마킹', desc: '시술 부위 격자 표시' },
        { step: 4, title: '시술', desc: 'AccuREP 기술로 맞춤 에너지 전달' },
        { step: 5, title: '마무리', desc: '시술 부위 진정 및 애프터케어 안내' },
      ],
      duration: '45-60분',
      anesthesia: '무마취 (진동 기술로 통증 감소)',
      recovery: '즉시 일상 복귀 가능',
      results: '즉각적 탄력 개선, 3-6개월 콜라겐 재생',
      targetAreas: ['얼굴 전체', '눈가', '목', '바디'],
      idealFor: [
        '피부 탄력 저하가 고민인 분',
        '잔주름 개선을 원하는 분',
        '자연스럽고 점진적인 변화를 원하는 분',
        '무마취 시술을 원하는 분',
      ],
      cautions: [
        '시술 후 일시적인 홍조가 있을 수 있음',
        '페이스메이커 장착자는 시술 불가',
        '임산부, 수유부는 시술 불가',
        '시술 부위에 금속 임플란트가 있는 경우 상담 필요',
      ],
      faqs: [
        { q: '써마지 FLX와 이전 버전의 차이는?', a: '4세대 FLX는 AccuREP 기술로 피부 상태에 맞는 에너지를 자동 조절하며, 시술 시간이 25% 단축되고 통증도 감소했습니다.' },
        { q: '시술 주기는 어떻게 되나요?', a: '일반적으로 1년에 1-2회 시술을 권장합니다. 피부 상태에 따라 달라질 수 있으므로 상담을 통해 결정합니다.' },
        { q: '써마지 눈가 시술도 가능한가요?', a: '네, 써마지 아이(Thermage Eye)는 눈가 전용 팁으로 눈꺼풀과 눈밑 탄력 개선에 효과적입니다.' },
      ],
      relatedTreatments: ['ulthera', 'inmode', 'density'],
    },
    density: {
      id: 'density',
      category: 'lifting',
      name: '덴서티',
      nameEn: 'Density',
      tagline: '고주파 에너지로 촘촘하게 – 정밀한 콜라겐 리프팅 솔루션',
      shortDesc: '고주파(RF) 에너지로 균일하고 매끄러운 리프팅',
      heroImage: '/images/treatments/density-hero.jpg',
      description: '덴서티는 고주파(RF) 에너지를 진피층에 집중 전달하여, 피부 깊은 곳의 콜라겐을 자극하고 피부 탄력과 주름 개선을 유도하는 고주파 리프팅 장비입니다. 일정한 깊이로 고르게 전달되는 에너지 덕분에 보다 균일하고 매끄러운 리프팅 효과를 기대할 수 있습니다.',
      benefits: [
        { title: '고주파 리프팅', desc: '고주파 방식으로 통증과 자극이 적음' },
        { title: '균일한 에너지', desc: '정밀하고 균일한 에너지 분포' },
        { title: '합리적 비용', desc: '써마지 대비 부담 적은 가격대' },
        { title: '정기적 관리', desc: '꾸준한 리프팅 관리에 적합' },
      ],
      process: [
        { step: 1, title: '상담', desc: '피부 상태 분석 및 시술 계획 수립' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 피부 정돈' },
        { step: 3, title: '마취', desc: '필요시 마취 크림 도포' },
        { step: 4, title: '시술', desc: 'RF 고주파 리프팅 진행' },
        { step: 5, title: '마무리', desc: '시술 부위 진정 및 애프터케어' },
      ],
      duration: '40-60분',
      anesthesia: '마취 크림 (선택)',
      recovery: '즉시 일상 복귀 가능',
      results: '즉각적 리프팅 + 3-6개월 콜라겐 재생',
      targetAreas: ['이마', '눈가', '볼', '턱선', '목'],
      idealFor: [
        '복합적인 리프팅 효과를 원하는 분',
        '즉각적인 효과와 장기적 개선을 모두 원하는 분',
        '기존 리프팅 시술에 만족하지 못한 분',
      ],
      cautions: [
        '시술 후 약간의 붓기, 홍조 가능',
        '피부 상태에 따라 시술 가능 여부 상담 필요',
        '임산부, 수유부는 시술 불가',
      ],
      faqs: [
        { q: '울쎄라피 프라임, 써마지와 어떤 차이가 있나요?', a: '덴서티는 써마지와 같은 고주파(RF) 리프팅 계열이지만, 보다 합리적인 비용과 낮은 통증으로 리프팅 관리를 시작하기에 적합한 장비입니다. 울쎄라피 프라임, 슈링크 같은 HIFU 계열과 병행 시 다양한 층을 아우르는 복합 탄력 시술도 가능합니다.' },
        { q: '시술 간격은 어느 정도가 좋은가요?', a: '일반적으로 3-6개월 간격으로 시술을 권장하며, 피부 상태에 따라 조절됩니다.' },
      ],
      relatedTreatments: ['ulthera', 'thermage', 'inmode'],
    },
    inmode: {
      id: 'inmode',
      category: 'lifting',
      name: '인모드',
      nameEn: 'InMode',
      tagline: '지방 감소 + 탄력 개선을 한 번에 – 스마트 고주파 리프팅',
      shortDesc: 'RF 에너지로 지방 감소와 리프팅 동시에',
      heroImage: '/images/treatments/inmode-hero.jpg',
      description: '인모드는 고주파(RF) 에너지를 활용해 지방층과 진피층을 동시에 자극, 리프팅과 동시에 슬리밍 효과까지 기대할 수 있는 멀티 리프팅 장비입니다. 얼굴 지방이 많은 타입이나 늘어진 피부가 복합적으로 고민인 경우에 효과적입니다.',
      benefits: [
        { title: '듀얼 효과', desc: '지방을 녹이고 리프팅까지 가능한 고주파 기술' },
        { title: '국소 집중', desc: '국소 부위 집중 시술 가능' },
        { title: '빠른 회복', desc: '통증과 다운타임 적음' },
        { title: '시너지 효과', desc: '써마지와 병행 시 고주파 시너지 효과 강화' },
      ],
      process: [
        { step: 1, title: '상담', desc: '피부 상태 분석 및 맞춤 핸드피스 선택' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 피부 정돈' },
        { step: 3, title: '마취', desc: '시술 종류에 따라 국소 마취' },
        { step: 4, title: '시술', desc: '선택한 핸드피스로 맞춤 시술' },
        { step: 5, title: '마무리', desc: '시술 부위 진정 및 애프터케어' },
      ],
      duration: '30-60분',
      anesthesia: '무마취 또는 마취 크림',
      recovery: '즉시 일상 복귀 가능',
      results: '즉각적 탄력 + 점진적 콜라겐 재생',
      targetAreas: ['턱밑', '볼살', '페이스라인', '이중턱', '심부볼'],
      idealFor: [
        '턱 밑 지방 제거 및 탄력 강화를 원하는 분',
        '볼살 리프팅 및 페이스라인 정리를 원하는 분',
        '이중턱, 심부볼 개선을 원하는 분',
        '피부 속 콜라겐 재생 및 잔주름 개선을 원하는 분',
      ],
      cautions: [
        '시술 후 약간의 붓기, 홍조 가능',
        '피부 상태에 따라 시술 가능 여부 상담 필요',
        '임산부, 수유부는 시술 불가',
      ],
      faqs: [
        { q: '인모드는 어떤 분께 추천하나요?', a: '얼굴 지방이 많거나 늘어진 피부가 복합적으로 고민인 분께 추천드립니다. 지방층과 진피층을 동시에 자극하여 리프팅과 슬리밍 효과를 동시에 기대할 수 있습니다.' },
        { q: '써마지와 병행하면 효과가 더 좋나요?', a: '네, 인모드와 써마지를 병행하면 고주파 시너지 효과로 더 강력한 탄력 개선을 기대할 수 있습니다.' },
      ],
      relatedTreatments: ['thermage', 'density', 'thread'],
    },
    shurink: {
      id: 'shurink',
      category: 'lifting',
      name: '슈링크',
      nameEn: 'Shurink',
      tagline: '데일리 리프팅의 대표 주자',
      shortDesc: '합리적인 초음파 탄력 시술',
      heroImage: '/images/treatments/shurink-hero.jpg',
      description: '슈링크는 울쎄라피 프라임과 동일한 HIFU(고강도 집속 초음파) 기술을 기반으로, 보다 합리적인 비용으로 반복 관리가 가능한 리프팅 장비입니다. 얕은 층부터 깊은 층까지 골고루 작용하여, 탄력 개선과 피부결 정리 효과를 동시에 기대할 수 있습니다.',
      benefits: [
        { title: '빠른 시술', desc: '고속 연사 방식으로 시술 시간 단축' },
        { title: '다양한 카트리지', desc: '부위별 최적화된 카트리지 제공' },
        { title: '정밀 조사', desc: '섬세한 에너지 조절 가능' },
        { title: '합리적 비용', desc: '효과 대비 합리적인 가격' },
      ],
      process: [
        { step: 1, title: '상담', desc: '피부 상태 분석 및 시술 계획 수립' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 피부 정돈' },
        { step: 3, title: '마취', desc: '마취 크림 도포 (선택)' },
        { step: 4, title: '시술', desc: '부위별 맞춤 카트리지로 시술' },
        { step: 5, title: '마무리', desc: '시술 부위 진정 및 애프터케어' },
      ],
      duration: '30-45분',
      anesthesia: '마취 크림 (선택)',
      recovery: '즉시 일상 복귀 가능',
      results: '2-4주 후 효과 시작, 3개월 최대 효과',
      targetAreas: ['이마', '눈가', '볼', '턱선', '목'],
      idealFor: [
        '처음 리프팅 시술을 받는 분',
        '빠른 시술을 원하는 분',
        '합리적인 비용으로 리프팅을 원하는 분',
        '정기적인 유지 관리를 원하는 분',
      ],
      cautions: [
        '시술 후 약간의 홍조 가능',
        '민감한 피부는 상담 필요',
        '임산부, 수유부는 시술 불가',
      ],
      faqs: [
        { q: '울쎄라피 프라임과 슈링크의 차이는?', a: '둘 다 HIFU 원리이지만, 울쎄라피 프라임은 DeepSEE 시각화 기술이 있고 더 깊은 층까지 도달합니다. 슈링크는 빠르고 합리적인 비용으로 정기적 관리에 적합합니다.' },
        { q: '시술 주기는 어떻게 되나요?', a: '보통 3-6개월 간격으로 시술을 권장하며, 울쎄라피 프라임이나 써마지 사이 유지 관리용으로도 좋습니다.' },
      ],
      relatedTreatments: ['ulthera', 'thermage', 'density'],
    },
    thread: {
      id: 'thread',
      category: 'lifting',
      name: '실리프팅',
      nameEn: 'Thread Lifting',
      tagline: '즉각적인 볼륨 리프팅',
      shortDesc: '녹는 실로 완성하는 V라인 리프팅',
      heroImage: '/images/treatments/thread-hero.jpg',
      description: '실리프팅은 PDO, PLLA, PCL 등 체내에서 녹는 특수 실을 사용하여 피부를 물리적으로 당겨 올리는 시술입니다. 즉각적인 리프팅 효과와 함께 실이 녹으면서 콜라겐 생성을 촉진합니다.',
      benefits: [
        { title: '즉각적 효과', desc: '시술 직후 리프팅 효과 확인 가능' },
        { title: '콜라겐 촉진', desc: '실이 녹으면서 콜라겐 재생 유도' },
        { title: '자연스러운 결과', desc: '점진적으로 효과가 자리잡아 자연스러움' },
        { title: '복합 효과', desc: '리프팅 + 탄력 개선 동시 효과' },
      ],
      process: [
        { step: 1, title: '상담', desc: '얼굴 구조 분석 및 실 종류 결정' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 소독' },
        { step: 3, title: '마취', desc: '시술 부위 국소 마취' },
        { step: 4, title: '시술', desc: '디자인에 따라 실 삽입' },
        { step: 5, title: '마무리', desc: '시술 부위 정돈 및 관리 안내' },
      ],
      duration: '30-60분',
      anesthesia: '국소 마취',
      recovery: '3-7일 (멍, 붓기 가능)',
      results: '즉각적 리프팅, 6-12개월 유지',
      targetAreas: ['이마', '광대', '볼', '턱선', '팔자', '목'],
      idealFor: [
        '즉각적인 리프팅을 원하는 분',
        '처진 볼살, 무너진 광대가 고민인 분',
        '팔자주름, 턱선 정리를 원하는 분',
        '레이저 리프팅만으로 만족스럽지 않은 분',
      ],
      cautions: [
        '시술 후 3-7일 멍, 붓기 가능',
        '2주간 과격한 표정, 마사지 피해야 함',
        '시술 부위 당김감이 있을 수 있음',
        '드물게 감염, 실 노출 가능성',
      ],
      faqs: [
        { q: '실리프팅은 얼마나 유지되나요?', a: '실 종류에 따라 다르지만, 보통 6-12개월 정도 효과가 유지됩니다. PDO는 6-8개월, PLLA/PCL은 12개월 이상 유지됩니다.' },
        { q: '실리프팅 후 언제부터 화장이 가능한가요?', a: '시술 24시간 후부터 가벼운 화장이 가능하며, 시술 부위는 1주일 정도 피해주시는 것이 좋습니다.' },
        { q: '레이저 리프팅과 병행해도 되나요?', a: '네, 실리프팅 후 1-2주 뒤에 레이저 리프팅을 병행하면 시너지 효과를 볼 수 있습니다.' },
      ],
      relatedTreatments: ['ulthera', 'thermage', 'filler'],
    },
    aptos: {
      id: 'aptos',
      category: 'lifting',
      name: '압토스 나미카',
      nameEn: 'APTOS NAMICA',
      tagline: '4세대 바이오 리프팅',
      shortDesc: '글로벌 100개국 이상 사용, KFDA 4등급 정식 허가',
      heroImage: '/images/aptos/procedure-main.jpg',
      description: 'APTOS NAMICA는 히알루론산 40mg을 나노, 서브마이크로, 마이크로 단위로 캡슐화하여 단계별로 방출하는 혁신적인 약물 전달 시스템(NAMICA Technology)을 적용한 4세대 바이오 실 리프팅입니다.',
      benefits: [
        { title: 'NAMICA 기술', desc: '히알루론산 40mg 단계별 방출 시스템' },
        { title: '글로벌 인증', desc: 'KFDA 4등급, CE, ISO 13485, FDA MDSAP' },
        { title: '장기 지속', desc: '최대 24개월 효과 지속' },
        { title: '바이오스티뮬레이션', desc: '콜라겐 생성 촉진으로 자연스러운 탄력' },
      ],
      process: [
        { step: 1, title: '상담', desc: '얼굴 구조 분석 및 시술 계획 수립' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 소독' },
        { step: 3, title: '마취', desc: '시술 부위 국소 마취' },
        { step: 4, title: '시술', desc: 'APTOS 실 삽입 및 리프팅' },
        { step: 5, title: '마무리', desc: '시술 부위 정돈 및 관리 안내' },
      ],
      duration: '30-60분',
      anesthesia: '국소 마취',
      recovery: '3-7일 (멍, 붓기 가능)',
      results: '즉각적 리프팅, 최대 24개월 유지',
      targetAreas: ['이마', '광대', '볼', '턱선', '팔자', '목'],
      idealFor: [
        '장기간 지속되는 리프팅을 원하는 분',
        '바이오스티뮬레이션 효과를 원하는 분',
        '글로벌 인증 제품을 원하는 분',
        '자연스러운 볼륨감과 탄력을 원하는 분',
      ],
      cautions: [
        '시술 후 3-7일 멍, 붓기 가능',
        '2주간 과격한 표정, 마사지 피해야 함',
        '시술 부위 당김감이 있을 수 있음',
        '드물게 감염, 실 노출 가능성',
      ],
      faqs: [
        { q: 'APTOS NAMICA는 일반 실리프팅과 어떻게 다른가요?', a: 'APTOS NAMICA는 히알루론산 40mg이 캡슐화되어 있어 즉각, 중기, 장기 3단계로 효과가 나타납니다. 또한 콜라겐 생성을 촉진하는 바이오스티뮬레이션 효과가 있어 최대 24개월까지 효과가 지속됩니다.' },
        { q: 'APTOS는 어떤 인증을 받았나요?', a: 'KFDA 의료기기 4등급 정식 허가, 유럽 CE 인증, ISO 13485 품질경영시스템, FDA MDSAP 인증을 받은 글로벌 표준 제품입니다.' },
        { q: '레이저 리프팅과 병행해도 되나요?', a: '네, APTOS 시술 후 2-4주 뒤에 레이저 리프팅을 병행하면 시너지 효과를 볼 수 있습니다.' },
      ],
      relatedTreatments: ['thread', 'ulthera', 'thermage'],
    },
  },
  // 안티에이징 시술
  antiaging: {
    botox: {
      id: 'botox',
      category: 'antiaging',
      name: '보톡스',
      nameEn: 'Botox',
      tagline: '표정 주름의 완벽한 해결책',
      shortDesc: '자연스러운 주름 개선과 윤곽 정리',
      heroImage: '/images/treatments/botox-hero.jpg',
      description: '보톡스(보툴리눔 톡신)는 근육의 움직임을 일시적으로 약화시켜 표정에 의한 주름을 개선하고, 턱근육(사각턱)이나 종아리 근육의 볼륨을 줄여주는 시술입니다. 정품 제품과 정확한 용량으로 자연스러운 결과를 제공합니다.',
      benefits: [
        { title: '표정 주름 개선', desc: '이마, 미간, 눈가 주름을 효과적으로 완화' },
        { title: '윤곽 정리', desc: '사각턱, 승모근 볼륨 감소' },
        { title: '빠른 시술', desc: '10-20분 내외의 짧은 시술 시간' },
        { title: '자연스러운 표정', desc: '적정 용량으로 자연스러운 표정 유지' },
      ],
      process: [
        { step: 1, title: '상담', desc: '주름 분석 및 원하는 결과 상담' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 소독' },
        { step: 3, title: '마취', desc: '필요시 마취 크림 도포' },
        { step: 4, title: '마킹', desc: '시술 포인트 표시' },
        { step: 5, title: '시술', desc: '미세 주사로 보톡스 주입' },
        { step: 6, title: '마무리', desc: '주의사항 안내' },
      ],
      duration: '10-20분',
      anesthesia: '무마취 또는 마취 크림 (원하시는 경우)',
      recovery: '즉시 일상 복귀',
      results: '3-7일 후 효과 시작, 3-6개월 유지',
      targetAreas: ['이마', '미간', '눈가', '사각턱', '입꼬리', '승모근', '종아리'],
      idealFor: [
        '표정 주름이 고민인 분',
        '사각턱, 승모근 볼륨 축소를 원하는 분',
        '빠르고 간편한 시술을 원하는 분',
        '예방적 안티에이징을 원하는 젊은 층',
      ],
      cautions: [
        '시술 당일 음주, 사우나 피해야 함',
        '시술 부위 마사지 금지',
        '임산부, 수유부, 신경근육 질환자 시술 불가',
      ],
      faqs: [
        { q: '보톡스 맞으면 표정이 부자연스러워지나요?', a: '적정 용량을 정확한 위치에 주입하면 자연스러운 표정을 유지하면서 주름만 개선됩니다. 과용량 사용시 부자연스러울 수 있어 숙련된 의료진의 시술이 중요합니다.' },
        { q: '보톡스 효과는 얼마나 유지되나요?', a: '개인차가 있지만 보통 3-6개월 정도 유지됩니다. 정기적으로 시술받으면 근육이 약화되어 효과가 더 오래갈 수 있습니다.' },
        { q: '보톡스 종류에 따라 차이가 있나요?', a: '제품마다 효과 발현 시간, 확산도, 지속 시간에 차이가 있습니다. 부위와 목적에 맞는 제품을 선택하는 것이 중요합니다.' },
      ],
      relatedTreatments: ['filler', 'skinbooster', 'thread'],
    },
    filler: {
      id: 'filler',
      category: 'antiaging',
      name: '필러',
      nameEn: 'Filler',
      tagline: '볼륨과 윤곽의 아트',
      shortDesc: '히알루론산으로 채우는 자연스러운 볼륨',
      heroImage: '/images/treatments/filler-hero.jpg',
      description: '필러는 히알루론산(HA)을 주성분으로 하여 꺼진 부위에 볼륨을 채우고, 주름을 개선하며, 윤곽을 정돈하는 시술입니다. 다양한 제품과 경도를 활용하여 부위별 맞춤 시술이 가능합니다.',
      benefits: [
        { title: '즉각적 효과', desc: '시술 직후 볼륨 개선 확인 가능' },
        { title: '자연스러운 촉감', desc: '히알루론산의 부드러운 질감' },
        { title: '가역적 시술', desc: '필요시 녹일 수 있어 안전' },
        { title: '다양한 적용', desc: '볼륨, 주름, 윤곽 등 다목적 사용' },
      ],
      process: [
        { step: 1, title: '상담', desc: '얼굴 분석 및 시술 계획 수립' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 소독' },
        { step: 3, title: '마취', desc: '시술 부위 마취 크림 또는 신경 차단' },
        { step: 4, title: '시술', desc: '부위별 맞춤 필러 주입' },
        { step: 5, title: '마무리', desc: '모양 정돈 및 애프터케어 안내' },
      ],
      duration: '20-40분',
      anesthesia: '마취 크림 또는 신경 차단 마취',
      recovery: '즉시 ~ 3일 (부위에 따라 상이)',
      results: '즉각적 효과, 6-24개월 유지 (제품에 따라 상이)',
      targetAreas: ['이마', '관자놀이', '코', '앞광대', '팔자', '옆볼', '턱끝', '애교살', '입술', '눈썹'],
      idealFor: [
        '꺼진 볼륨을 채우고 싶은 분',
        '팔자주름, 입가 주름이 고민인 분',
        '코, 턱 윤곽을 높이고 싶은 분',
        '입술 볼륨을 원하는 분',
      ],
      cautions: [
        '시술 후 멍, 붓기가 있을 수 있음',
        '시술 부위 마사지, 압박 금지',
        '과격한 운동, 사우나 3일간 피하기',
        '드물게 혈관 폐색 위험 있어 숙련된 의료진 시술 필수',
      ],
      faqs: [
        { q: '필러가 뭉치거나 부자연스러워지지 않나요?', a: '정품 필러를 적정량 사용하고 해부학적 지식을 갖춘 의료진이 시술하면 자연스러운 결과를 얻을 수 있습니다. 과도한 시술은 부자연스러울 수 있으니 적정량 시술이 중요합니다.' },
        { q: '필러 시술 후 바로 일상생활이 가능한가요?', a: '대부분 즉시 일상 복귀가 가능합니다. 다만 시술 부위에 따라 멍이나 붓기가 있을 수 있어 중요한 일정 전에는 여유를 두고 시술받는 것이 좋습니다.' },
        { q: '필러를 녹일 수 있나요?', a: '히알루론산 필러는 히알루로니다제로 녹일 수 있습니다. 시술 결과가 마음에 들지 않거나 합병증이 생겼을 때 안전하게 제거할 수 있습니다.' },
      ],
      relatedTreatments: ['botox', 'skinbooster', 'thread'],
    },
    skinbooster: {
      id: 'skinbooster',
      category: 'antiaging',
      name: '스킨부스터',
      nameEn: 'Skin Booster',
      tagline: '피부 속부터 차오르는 광채',
      shortDesc: '진피층 주입으로 수분, 재생, 탄력 개선',
      heroImage: '/images/treatments/skinbooster-hero.jpg',
      description: '스킨부스터는 다양한 제품을 피부 진피층에 주입하여 수분 공급, 재생, 탄력, 광채를 개선하는 시술입니다. 리쥬란, 쥬베룩, 리바이브, 비탈, 리투오 등 피부 상태에 맞는 제품을 선택하여 피부 컨디션을 끌어올립니다.',
      benefits: [
        { title: '깊은 수분 공급', desc: '진피층까지 히알루론산 전달' },
        { title: '피부 탄력 개선', desc: '콜라겐, 엘라스틴 생성 촉진' },
        { title: '자연스러운 광채', desc: '피부 속부터 건강한 빛' },
        { title: '피부결 개선', desc: '잔주름, 모공 개선 효과' },
      ],
      process: [
        { step: 1, title: '상담', desc: '피부 상태 분석 및 제품 선택' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 피부 정돈' },
        { step: 3, title: '마취', desc: '마취 크림 도포' },
        { step: 4, title: '시술', desc: '미세 주사 또는 기기로 주입' },
        { step: 5, title: '마무리', desc: '진정 케어 및 자외선 차단' },
      ],
      duration: '30-45분',
      anesthesia: '마취 크림',
      recovery: '1-3일 (미세 주사 자국)',
      results: '2-4주 후 효과, 3-4회 코스 권장',
      targetAreas: ['얼굴 전체', '목', '손등'],
      idealFor: [
        '피부 건조함, 수분 부족이 고민인 분',
        '피부 탄력 저하, 잔주름이 고민인 분',
        '칙칙한 피부톤, 생기 없는 피부가 고민인 분',
        '레이저 시술 후 피부 재생을 원하는 분',
      ],
      cautions: [
        '시술 후 미세 주사 자국, 붉은기 가능',
        '시술 당일 화장, 음주 피하기',
        '자외선 차단 철저히 하기',
        '2-4주 간격으로 3-4회 시술 권장',
      ],
      faqs: [
        { q: '스킨부스터와 물광주사는 같은 건가요?', a: '비슷한 개념이지만, 스킨부스터는 다양한 성분(히알루론산, 폴리뉴클레오타이드 등)을 포함합니다. 물광주사는 주로 히알루론산 기반의 수분 공급에 초점을 맞춥니다.' },
        { q: '효과는 언제부터 나타나나요?', a: '시술 직후에도 수분감을 느낄 수 있으며, 2-4주 후부터 피부 탄력, 광채가 개선됩니다. 최적의 효과를 위해 2-4주 간격으로 3-4회 시술을 권장합니다.' },
        { q: '어떤 제품이 좋은가요?', a: '리쥬란, 쥬베룩, 리바이브, 비탈, 리투오 등 다양한 제품이 있으며, 피부 상태와 목적에 따라 선택합니다. 상담을 통해 본인에게 맞는 제품을 결정합니다.' },
      ],
      relatedTreatments: ['botox', 'filler', 'laser'],
    },
  },
  // 레이저 시술
  laser: {
    clarity: {
      id: 'clarity',
      category: 'laser',
      name: '클래리티 II',
      nameEn: 'Clarity II',
      tagline: '듀얼 파장 레이저의 정점',
      shortDesc: '색소, 혈관, 제모까지 멀티 솔루션',
      heroImage: '/images/treatments/clarity-hero.jpg',
      description: '클래리티 II는 755nm 알렉산드라이트와 1064nm Nd:YAG 듀얼 파장을 탑재한 프리미엄 레이저입니다. 색소 치료, 혈관 치료, 제모까지 다양한 피부 고민을 효과적으로 해결합니다.',
      benefits: [
        { title: '듀얼 파장', desc: '755nm + 1064nm 멀티 솔루션' },
        { title: '정밀 색소 치료', desc: '기미, 잡티, 주근깨 개선' },
        { title: '혈관 치료', desc: '홍조, 모세혈관 확장 개선' },
        { title: '안전한 시술', desc: 'IntelliTrak 기술로 정밀 제어' },
      ],
      process: [
        { step: 1, title: '상담', desc: '피부 분석 및 시술 계획' },
        { step: 2, title: '세안', desc: '메이크업 제거 및 피부 정돈' },
        { step: 3, title: '시술', desc: '레이저 조사' },
        { step: 4, title: '쿨링', desc: '시술 부위 진정' },
        { step: 5, title: '마무리', desc: '자외선 차단 및 관리 안내' },
      ],
      duration: '15-30분',
      anesthesia: '무마취 또는 마취 크림',
      recovery: '3-5일 (색소 부위 딱지 가능)',
      results: '2-4주 간격 3-5회 시술 권장',
      targetAreas: ['얼굴 전체', '색소 부위', '혈관 부위'],
      idealFor: [
        '기미, 잡티가 고민인 분',
        '홍조, 혈관 확장이 있는 분',
        '전체적인 피부톤 개선을 원하는 분',
        '레이저 제모를 원하는 분',
      ],
      cautions: [
        '시술 후 자외선 차단 필수',
        '일시적 색소 침착 가능',
        '시술 간격 2-4주 유지',
      ],
      faqs: [
        { q: '클래리티 II의 장점은?', a: '듀얼 파장으로 다양한 피부 타입과 색소 깊이에 맞춤 치료가 가능하며, 안전하고 효과적인 시술이 가능합니다.' },
        { q: '몇 회 시술이 필요한가요?', a: '색소 깊이와 종류에 따라 다르지만, 보통 2-4주 간격으로 3-5회 시술을 권장합니다.' },
      ],
      relatedTreatments: ['skinbooster', 'thermage'],
    },
  },
} as const;

// 의료정보 Q&A
export const MEDICAL_QA = [
  {
    id: 'ulthera-vs-thermage',
    category: 'lifting',
    question: '울쎄라피 프라임과 써마지의 차이점은 무엇인가요?',
    answer: '울쎄라피 프라임은 HIFU(고강도 집속 초음파) 기술을 사용하여 피부 깊은 층인 SMAS까지 에너지를 전달합니다. 반면 써마지는 RF(고주파) 에너지를 사용하여 진피층의 콜라겐을 수축시키고 재생을 촉진합니다. 울쎄라피 프라임은 처진 피부의 리프팅에 효과적이고, 써마지는 전반적인 피부 탄력 개선에 효과적입니다. 두 시술을 병행하면 시너지 효과를 볼 수 있습니다.',
    relatedTreatments: ['ulthera', 'thermage'],
    tags: ['울쎄라피 프라임', '써마지', '리프팅', 'HIFU', '고주파'],
  },
  {
    id: 'lifting-pain',
    category: 'lifting',
    question: '리프팅 시술은 얼마나 아픈가요?',
    answer: '리프팅 시술의 통증은 시술 종류와 개인차에 따라 다릅니다. 울쎄라피 프라임과 써마지 FLX 모두 시술 전 마취 크림을 30분 정도 바른 후 진행합니다. 특히 써마지 FLX는 진동 기술(Vibrating Tip)이 적용되어 통증이 크게 감소했으며, 대부분의 환자분들이 편안하게 시술을 받으실 수 있습니다. 통증에 민감하신 분은 추가적인 통증 조절이 가능하니 상담 시 말씀해주세요.',
    relatedTreatments: ['ulthera', 'thermage', 'shurink'],
    tags: ['리프팅', '통증', '마취'],
  },
  {
    id: 'lifting-frequency',
    category: 'lifting',
    question: '리프팅 시술은 얼마나 자주 받아야 하나요?',
    answer: '울쎄라피 프라임은 1-2년에 1회, 써마지는 6개월-1년에 1회를 권장합니다. 슈링크나 인모드 등 유지 관리용 시술은 3-6개월 간격으로 받으실 수 있습니다. 피부 상태와 원하시는 효과에 따라 시술 주기가 달라질 수 있으므로, 정확한 주기는 상담을 통해 결정하시는 것이 좋습니다.',
    relatedTreatments: ['ulthera', 'thermage', 'shurink'],
    tags: ['리프팅', '시술주기', '유지관리'],
  },
  {
    id: 'lifting-duration',
    category: 'lifting',
    question: '리프팅 효과는 얼마나 지속되나요?',
    answer: '울쎄라피 프라임의 효과는 약 1년, 써마지는 6개월-1년 정도 지속됩니다. 다만 효과 지속 기간은 개인의 피부 상태, 나이, 생활 습관에 따라 달라질 수 있습니다. 정기적인 유지 관리 시술을 받으시면 효과를 더 오래 유지할 수 있습니다.',
    relatedTreatments: ['ulthera', 'thermage'],
    tags: ['리프팅', '효과지속', '유지기간'],
  },
  {
    id: 'botox-natural',
    category: 'antiaging',
    question: '보톡스 맞으면 표정이 부자연스러워지나요?',
    answer: '적정 용량을 정확한 위치에 주입하면 자연스러운 표정을 유지하면서 주름만 개선됩니다. 부자연스러운 표정은 주로 과용량 사용이나 잘못된 주입 위치로 인해 발생합니다. 리브성형외과에서는 숙련된 전문의가 개인의 근육 특성에 맞춰 적정량을 시술하므로 자연스러운 결과를 기대하실 수 있습니다.',
    relatedTreatments: ['botox'],
    tags: ['보톡스', '표정', '자연스러움'],
  },
  {
    id: 'botox-duration',
    category: 'antiaging',
    question: '보톡스 효과는 얼마나 지속되나요?',
    answer: '보톡스 효과는 개인차가 있지만 보통 3-6개월 정도 지속됩니다. 정기적으로 시술받으면 근육이 점차 약화되어 효과가 더 오래 지속되고, 시술 간격도 늘어날 수 있습니다. 첫 시술 후 2-3주 뒤 추가 터치업이 필요할 수 있으니, 경과를 확인하시는 것이 좋습니다.',
    relatedTreatments: ['botox'],
    tags: ['보톡스', '효과지속', '시술주기'],
  },
  {
    id: 'filler-dissolve',
    category: 'antiaging',
    question: '필러는 녹일 수 있나요?',
    answer: '네, 히알루론산 필러는 히알루로니다제(녹이는 주사)로 녹일 수 있습니다. 시술 결과가 마음에 들지 않거나 부작용이 발생했을 때 안전하게 제거할 수 있습니다. 이것이 히알루론산 필러의 큰 장점 중 하나입니다. 다만 비가역적 필러(예: 아테콜)는 녹일 수 없으므로, 필러 선택 시 이 점을 고려하셔야 합니다.',
    relatedTreatments: ['filler'],
    tags: ['필러', '히알루론산', '녹이는주사'],
  },
  {
    id: 'filler-lumps',
    category: 'antiaging',
    question: '필러가 뭉치거나 울퉁불퉁해질 수 있나요?',
    answer: '정품 필러를 적정량 사용하고, 해부학적 지식을 갖춘 숙련된 의료진이 시술하면 이런 문제가 거의 발생하지 않습니다. 간혹 발생하는 울퉁불퉁함은 대부분 마사지로 해결되며, 필요시 히알루로니다제로 조절할 수 있습니다. 시술 후 불편하신 점이 있으면 바로 상담해주세요.',
    relatedTreatments: ['filler'],
    tags: ['필러', '부작용', '뭉침'],
  },
  {
    id: 'skinbooster-frequency',
    category: 'antiaging',
    question: '스킨부스터는 몇 회 맞아야 효과가 있나요?',
    answer: '스킨부스터는 2-4주 간격으로 3-4회 시술을 기본 코스로 권장합니다. 1회 시술 후에도 수분감 개선을 느낄 수 있지만, 최적의 효과를 위해서는 코스 시술이 필요합니다. 이후에는 2-3개월마다 유지 시술을 받으시면 좋습니다.',
    relatedTreatments: ['skinbooster'],
    tags: ['스킨부스터', '물광주사', '시술횟수'],
  },
  {
    id: 'laser-sun',
    category: 'laser',
    question: '레이저 시술 후 햇빛을 피해야 하나요?',
    answer: '네, 레이저 시술 후에는 자외선 차단이 매우 중요합니다. 시술 후 피부가 민감해져 자외선에 의한 색소침착 위험이 높아집니다. 최소 2-4주간은 자외선 차단제(SPF 50+)를 꼼꼼히 바르고, 모자나 양산을 사용하시는 것이 좋습니다. 야외 활동이 많은 시기에는 레이저 시술을 피하시는 것이 좋습니다.',
    relatedTreatments: ['clarity'],
    tags: ['레이저', '자외선', '색소침착'],
  },
  {
    id: 'laser-downtime',
    category: 'laser',
    question: '레이저 시술 후 다운타임은 어느 정도인가요?',
    answer: '레이저 종류에 따라 다릅니다. 레이저 토닝의 경우 거의 다운타임이 없어 바로 일상생활이 가능합니다. 클래리티 II 레이저로 표피 색소를 치료한 경우 3-5일 정도 색소가 진해지거나 얇은 딱지가 생겼다가 자연스럽게 떨어집니다.',
    relatedTreatments: ['clarity'],
    tags: ['레이저', '다운타임', '회복기간'],
  },
  {
    id: 'thread-duration',
    category: 'lifting',
    question: '실리프팅 효과는 얼마나 유지되나요?',
    answer: '실 종류에 따라 다릅니다. PDO(녹는 실)는 6-8개월, PLLA나 PCL 실은 12-18개월 정도 효과가 유지됩니다. 실이 녹으면서 콜라겐 재생을 촉진하므로, 실이 완전히 녹은 후에도 일정 기간 효과가 유지됩니다. 정기적인 유지 시술을 통해 효과를 지속시킬 수 있습니다.',
    relatedTreatments: ['thread'],
    tags: ['실리프팅', '효과지속', 'PDO'],
  },
  {
    id: 'consultation-fee',
    category: 'general',
    question: '상담만 받아도 되나요? 비용이 있나요?',
    answer: '네, 상담만 받으셔도 됩니다. 1:1 전문 상담비용은 1만원이며, 당일 시술 진행 시 시술 금액에서 전액 차감됩니다. 성형외과 전문의가 직접 피부 상태를 진단하고 최적의 시술 플랜을 제안해 드립니다. 충분히 고민하신 후 결정하셔도 괜찮습니다.',
    relatedTreatments: [],
    tags: ['상담', '상담비', '예약'],
  },
  {
    id: 'payment-installment',
    category: 'general',
    question: '시술 비용 할부가 가능한가요?',
    answer: '네, 카드 할부 결제가 가능합니다. 무이자 할부 혜택은 카드사와 결제 금액에 따라 다를 수 있으니, 상담 시 문의해주세요. 또한 시술별로 다양한 프로모션과 패키지 할인도 있으니 확인해보시기 바랍니다.',
    relatedTreatments: [],
    tags: ['비용', '할부', '결제'],
  },
  {
    id: 'pregnant-treatment',
    category: 'general',
    question: '임신 중이나 수유 중에도 시술이 가능한가요?',
    answer: '임신 중이나 수유 중에는 대부분의 미용 시술이 권장되지 않습니다. 보톡스, 필러, 리프팅 시술 모두 태아나 모유에 미치는 영향에 대한 안전성이 충분히 검증되지 않았기 때문입니다. 임신과 수유를 마친 후에 시술받으시는 것을 권장합니다.',
    relatedTreatments: [],
    tags: ['임신', '수유', '금기사항'],
  },
] as const;

// 메인 네비게이션
export const MAIN_NAV = [
  {
    label: '리브 소개',
    href: '/about',
    children: [
      { label: '리브 브랜드', href: '/about' },
      { label: '의료진 소개', href: '/about/staff' },
      { label: '보유 장비', href: '/about/equipment' },
      { label: '오시는 길', href: '/about/location' },
    ],
  },
  {
    label: '시그니처',
    href: '/signature',
  },
  {
    label: '리프팅',
    href: '/lifting',
    children: [
      { label: '울쎄라피 프라임', href: '/lifting/ulthera' },
      { label: '써마지 FLX', href: '/lifting/thermage' },
      { label: '덴서티', href: '/lifting/density' },
      { label: '인모드', href: '/lifting/inmode' },
      { label: '슈링크', href: '/lifting/shurink' },
      { label: '실리프팅', href: '/lifting/thread' },
    ],
  },
  {
    label: '안티에이징',
    href: '/antiaging',
    children: [
      { label: '보톡스', href: '/antiaging/botox' },
      { label: '필러', href: '/antiaging/filler' },
      { label: '스킨부스터', href: '/antiaging/skinbooster' },
    ],
  },
  {
    label: '레이저',
    href: '/laser',
  },
  {
    label: '의료정보',
    href: '/medical',
  },
] as const;
